package com.example.composestarter.utils

object Constant {
    const val BASE_URL = "https://valorant-api.com/v1/"
    const val ROOM_DATA_BASE_NAME = "my_db"

    const val IS_AGENT_FAVORITE_MESSAGE_SHOWED = "IS_AGENT_FAVORITE_MESSAGE_SHOWED"
    const val IS_SKIN_FAVORITE_MESSAGE_SHOWED = "IS_SKIN_FAVORITE_MESSAGE_SHOWED"

    const val IS_AGENT_FAVORITE_REMOVE_MESSAGE_SHOWED = "IS_AGENT_FAVORITE_REMOVE_MESSAGE_SHOWED"
    const val IS_SKIN_FAVORITE_REMOVE_MESSAGE_SHOWED = "IS_AGENT_FAVORITE_REMOVE_MESSAGE_SHOWED"
}
